// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxuwqellfmcixohcklzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4dXdxZWxsZm1jaXhvaGNrbHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzE0MTMsImV4cCI6MjA1OTc0NzQxM30.AFnjZEPfcjfsmGZj0YxiX2hkYn4zH9JYIT55G7Kfjls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);